/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideoFeedRouteImport } from './routes/video/feed'
import { Route as VideoVideoIdRouteImport } from './routes/video/$videoId'
import { Route as UserUserIdRouteImport } from './routes/user/$userId'
import { Route as VideoUserUserIdRouteImport } from './routes/video/user.$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoFeedRoute = VideoFeedRouteImport.update({
  id: '/video/feed',
  path: '/video/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoVideoIdRoute = VideoVideoIdRouteImport.update({
  id: '/video/$videoId',
  path: '/video/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUserIdRoute = UserUserIdRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoUserUserIdRoute = VideoUserUserIdRouteImport.update({
  id: '/video/user/$userId',
  path: '/video/user/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/user/$userId': typeof UserUserIdRoute
  '/video/$videoId': typeof VideoVideoIdRoute
  '/video/feed': typeof VideoFeedRoute
  '/video/user/$userId': typeof VideoUserUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/user/$userId': typeof UserUserIdRoute
  '/video/$videoId': typeof VideoVideoIdRoute
  '/video/feed': typeof VideoFeedRoute
  '/video/user/$userId': typeof VideoUserUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/user/$userId': typeof UserUserIdRoute
  '/video/$videoId': typeof VideoVideoIdRoute
  '/video/feed': typeof VideoFeedRoute
  '/video/user/$userId': typeof VideoUserUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/user/$userId'
    | '/video/$videoId'
    | '/video/feed'
    | '/video/user/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/user/$userId'
    | '/video/$videoId'
    | '/video/feed'
    | '/video/user/$userId'
  id:
    | '__root__'
    | '/'
    | '/user/$userId'
    | '/video/$videoId'
    | '/video/feed'
    | '/video/user/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UserUserIdRoute: typeof UserUserIdRoute
  VideoVideoIdRoute: typeof VideoVideoIdRoute
  VideoFeedRoute: typeof VideoFeedRoute
  VideoUserUserIdRoute: typeof VideoUserUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/feed': {
      id: '/video/feed'
      path: '/video/feed'
      fullPath: '/video/feed'
      preLoaderRoute: typeof VideoFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/$videoId': {
      id: '/video/$videoId'
      path: '/video/$videoId'
      fullPath: '/video/$videoId'
      preLoaderRoute: typeof VideoVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$userId': {
      id: '/user/$userId'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof UserUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/user/$userId': {
      id: '/video/user/$userId'
      path: '/video/user/$userId'
      fullPath: '/video/user/$userId'
      preLoaderRoute: typeof VideoUserUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserUserIdRoute: UserUserIdRoute,
  VideoVideoIdRoute: VideoVideoIdRoute,
  VideoFeedRoute: VideoFeedRoute,
  VideoUserUserIdRoute: VideoUserUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
